#!/usr/bin/env bash
set -euo pipefail

export DOTFILES="${DOTFILES:-"${HOME}/dotfiles"}"
export PATH="${DOTFILES}/bin:${PATH}:/usr/local/bin:/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:${HOME}/bin"

##? Setups the environment
##?
##? Usage:
##?    install
##?
##? Env vars:
##?    DOTFILES
##?    HOMELAB_DOMAIN
##?    HOMELAB_PORT
##?
##? Examples:
##?    curl -sSL https://raw.githubusercontent.com/denisidoro/snippets/main/bash/install_dotfiles | bash
##?    wget -qO- https://raw.githubusercontent.com/denisidoro/snippets/main/bash/install_dotfiles | bash

_dot() {
   "${DOTFILES}/bin/dot" "$@"
}

has() {
   type "$1" &>/dev/null
}

log::info() {
   echo -e "\033[0;34m$*\033[0m" >&2
}

log::warn() {
   echo -e "\033[0;33m$*\033[0m" >&2
}

_install() {
   if has pkg; then
      sudo pkg install -y "$1"
   elif has apt-get; then
      sudo apt-get install --yes "$1"
   elif has yum; then
      sudo yum install "$1"
   elif has brew; then
      brew install "$1"
   elif has apk; then
      sudo apk install -y "$1"
   fi
}

_install_if_absent() {
   local -r pkg="$1"
   if has "$pkg"; then
     return 0
   fi
   _install "$pkg"
}

clone_repo() {
   _install_if_absent git
   export HOMELAB_DOMAIN="${HOMELAB_DOMAIN:-"$(ask_for "homelab domain")"}"
   export HOMELAB_PORT="${HOMELAB_PORT:-"$(ask_for "homelab port")"}"
   local repo="ssh://denis@${HOMELAB_DOMAIN}:${HOMELAB_PORT}/usr/share/hassio/backup/git/dotfiles"
   git clone "$repo" "$DOTFILES"
}

setup_ssh() {
   log::info "Setting up SSH..."

   _install_if_absent openssh || true

   local path
   path="${HOME}/.ssh/id_ed25519"
   if [ -f "$path" ]; then
      log::info "SSH key already exists!"
      return
   fi

   read -p "Enter the contents of ${path}.pub: " contents
   echo "$contents" > "${path}.pub"

   contents=""
   read -d $'\04' -p "Enter the contents of ${path}. Hit Ctrl-D to terminate the input: " contents
   echo "$contents" > "$path"

   eval "$(ssh-agent -s)"
   ssh-add "$path"
}

file_mentions_dotfiles() {
   if ! [ -f "$1" ]; then
      return 1
   fi
   grep -q 'dotfiles' "$1"
}

set_bashrc() {
   log::warn "Setting up bashrc..."

   for f in ~/.bashrc ~/.bash_profile; do
      if file_mentions_dotfiles "$f"; then
         log::warn "File already mentions dotfiles: $f"
         return 0
      fi
   done

   echo 'source "${HOME}/dotfiles/shell/bash/bashrc"' >> ~/.bash_profile
}

ask_for() {
   local var
   read -p "Set $1: " var
   echo "$var"
}

main() {
   log::info "Setting up..."

   setup_ssh

   if [ -d "$DOTFILES" ]; then
      log::warn "${DOTFILES} already exists!"
   else
      log::info "No dotfiles folder found. Cloning dotfiles..."
      clone_repo
   fi

   cd "$DOTFILES"

   log::info "Installing some key dependencies..."

   local is_android=false
   if uname -a | grep -q "ndroid"; then
      log::info "Bootstraping Android..."
      is_android=true
      _dot pkg add termux-essentials || true
   fi

   set_bashrc

   _dot pkg add git curl tar vi || true
   _dot pkg add vault || true

   if $is_android; then
      termux-chroot || true
   fi
}

case "${1:-}" in
   -h|--help|--version) grep "^##?" "$0" | cut -c 5-; exit 0 ;;
esac

if ! has sudo; then
   sudo() { "$@"; }
   export -f sudo
fi

set +e
main "$@"
